version: '4.5'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: "CoffeeMachine"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes: 
      - CoffeeMachine_db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CoffeeMachine"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  CoffeeMachine_db: